require "user.telescope"
require 'user.nordic'
require "user.project"
require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.lualine"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.mason_lsp"
require "user.autopairs"
require "user.comment"
require "user.alpha"
require "user.autocommands"
require "user.colorizer"
require "user.vimtex"
require 'user.lualine'
require 'user.undotree'
require 'user.vimwiki'
require 'user.ultisnips'
require 'user.quickscope'
require 'user.gitsigns'
require "user.todo"
require "user.lsp"
require "user.devcons"
require "user.markdownprev"
-- require "user.indentline"
require "user.zen"
require "user.toggleterm"
require 'user.treesitter'
require 'user.vimwiki_backlinks'
require 'user.vimwiki_link'
require 'user.vimwiki_better_sc'
require "user.copilot"
require 'user.harpoon'
require "user.goto_preview"
require "user.noice"
require "user.notify"
require "user.neogit"
require "user.gruvbox"
require 'user.nvim-tree'

