require 'user.vimtex'
-- require 'user.nordic'
-- require 'user.colorscheme'
require 'user.kanagawa'
require 'user.telescope'
require 'user.impatient'
require 'user.options'
require 'user.plugins'
require 'user.cmp'
require 'user.autopairs'
require 'user.comment'
require 'user.alpha'
require 'user.autocommands'
require 'user.colorizer'
require 'user.ultisnips'
require 'user.gitsigns'
require 'user.nvim_dap'
require 'user.nvim_dap_ui'
require 'user.mason_tools'
require 'user.lsp'
require 'user.lint'
require 'user.devcons'
require 'user.markdownprev'
require 'user.zen'
require 'user.toggleterm'
require 'user.copilot'
require 'user.harpoon'
require 'user.nvim-tree'
require 'user.treesitter'
require 'user.indentline'
require 'user.oil'
require 'user.vimwiki'
require 'user.keymaps'
require 'user.vimwiki_utils'
require 'user.undotree'
require 'user.neorunner'
require 'user.todo'
require 'user.headlines'
require 'user.lualine'
-- require 'user.noice'
-- require 'user.gruvbox'
-- require 'user.notify'
