require 'user.telescope'
require 'user.iron'
require 'user.todo'
require 'user.impatient'
require 'user.options'
require 'user.plugins'
require 'user.cmp'
require 'user.autopairs'
require 'user.comment'
require 'user.alpha'
require 'user.autocommands'
require 'user.gitsigns'
require 'user.nvim_dap'
require 'user.nvim_dap_ui'
require 'user.mason_tools'
require 'user.lsp'
require 'user.lint'
require 'user.devcons'
require 'user.markdownprev'
require 'user.toggleterm'
require 'user.harpoon'
require 'user.nvim-tree'
require 'user.treesitter'
require 'user.indentline'
require 'user.oil'
require 'user.keymaps'
require 'user.undotree'
require 'user.vimwiki_utils'
require 'user.ultisnips'
require "user.lint"
require 'user.colorscheme'
-- require 'user.smear'
require 'user.transparent'
require 'user.lualine'
require 'user.flash'
require 'user.zen'
require 'user.firenvim'
require 'user.vimtex'
require 'user.vimwiki'
require 'user.taskwarrior'


-- require 'user.render_markdown'
-- require 'user.colorizer'
-- require 'user.nordic'
-- require 'user.copilot'
