[colors]
black = #191D24
white = #dc8a78
grey = #242933
lightgrey = #3B4252
red = #BF616A
orange = #CB775D
yellow = #E7D49F
green = #A3BE8C
background = ${colors.black}
# background = #aa2F343F      # true transparency
background-alt = ${colors.orange}
foreground = ${colors.white}
inactive = ${colors.grey}
