[colors]
black = #191D24
white = #ECEFF4
grey = #242933
grey-1 = #2E3440
grey-2 = #3B4252
red = #BF616A
orange = #CB775D
yellow = #E7C173
blue = #5E81AC
green = #A3BE8C
background = ${colors.black}
# background = #aa2F343F      # true transparency
background-alt = ${colors.grey-1}
foreground = ${colors.white}
foreground-alt = ${colors.white}
inactive = ${colors.grey}
prefix = ${colors.yellow}
